---
title: "Applied GIS"
author: |
  | Yi Qiang
  | email: yi.qiang@hawaii.edu
date: '`r format(Sys.time(), "%B %d, %Y")`'
output: beamer_presentation
<<<<<<< HEAD
=======
fontsize: 12pt
>>>>>>> 5603d93081f13a82139bb883f43c1379a05b280f
---


## R Markdown

Course Topics

* Map Algebra in ArcGIS
* Suitability Modeling
    + General suitability modeling
    + Predictive habitat suitability modeling
* Land cover change modeling
    + Change and time-series analysis
    + Simulation
* Terrain and watershed analysis 
    + General terrain analysis techniques 
    + Stream and watershed delineation 
* 3D GIS
    + 3D data creation, visualization, analysis
    + Lidar data management, editing, and analysis 
  
<<<<<<< HEAD

## Approaches to Lectures & Demos 

- A bit of theory on certain new topics 
- Examples and case-studies from the readings 
- Review / demonstration of particular GIS analysis or software skills on as-needed basis 
- Compared to the other GIS courses, there will be much more time to work on lab assignments during scheduled class time 

## Readings

- Several required readings for each topic - most are journal articles 
- Most of the readings are closely related to the lab assignments - we can't cover all the advanced techniques from the literature, but doing the readings will help with the lab assignments, in particular answering the questions 
- Some readings use very advanced statistical methods or other non-GIS techniques - don't worry, you don't have to understand the nuts and bolts of each method - focus on the GIS elements

## Expected Knowledge: ArcGIS 

* Knowledge of the fundamentals of ArcGIS is required 
    - support will be provided by the instructor on a as needed basis. 
    - You will be given course codes for online ESRI Virtual Campus courses. 
* A basic knowledge of Spatial Analyst is required -we'll do more advanced stuff throughout this course. 

## Expected Knowledge: Vector and Raster Analysis Tools { .columns-2}
\begin{columns}
\begin{column}{0.48\textwidth}

\begin{itemize}
   \item Some text
   \begin{itemize}
    \item Some more text
  \end{itemize}
   \item Some more text
   \item blah, blah.
\end{itemize}
 
\end{column}
\begin{column}{0.48\textwidth}
Raster
2
3
4
\end{column}
\end{columns}
=======

## Approaches to Lectures & Demos 

- A bit of theory on certain new topics 
- Examples and case-studies from the readings 
- Review / demonstration of particular GIS analysis or software skills on as-needed basis 
- Compared to the other GIS courses, there will be much more time to work on lab assignments during scheduled class time 

## Readings

- Several required readings for each topic - most are journal articles 
- Most of the readings are closely related to the lab assignments - we can't cover all the advanced techniques from the literature, but doing the readings will help with the lab assignments, in particular answering the questions 
- Some readings use very advanced statistical methods or other non-GIS techniques - don't worry, you don't have to understand the nuts and bolts of each method - focus on the GIS elements

## Expected Knowledge: ArcGIS 

* Knowledge of the fundamentals of ArcGIS is required 
    - support will be provided by the instructor on a as needed basis. 
    - You will be given course codes for online ESRI Virtual Campus courses. 
* A basic knowledge of Spatial Analyst is required -we'll do more advanced stuff throughout this course. 

## Expected Knowledge: Vector and Raster Analysis Tools { .columns-2}
\begin{columns}
\begin{column}{0.48\textwidth}

\begin{itemize}
  \item Vector analysis tools
    \begin{itemize}
      \item Query (spatial/attribute)
      \item Join/relate
      \item Buffering
      \item Dissolve
      \item Merge
      \item Intersect
      \item union
    \end{itemize}
\end{itemize}
 
\end{column}
\begin{column}{0.48\textwidth}

\begin{itemize}
  \item Raster analysis tools
    \begin{itemize}
      \item Raster calculator
      \item Map algebra
      \item Reclassification
      \item Distance functions
      \item Zonal statisitcs
      \item Neighborhood
      \item Surface interpolation
    \end{itemize}
\end{itemize}
 
\end{column}
\end{columns}

## Expected Knowledge: Statistics & Remote Sensing
* Hands-on Knowledge of basic statistics is required, for example, exploratory statisitc analysis or simple linear regression analysis.
* Knowledge of advanced statistics will help with readings, but is not required.
* Knowledge of remote sensing is not required but useful.

## Lab Assignments
* Important part of this course
    + Learning-by-doing is essential for developing GIS skills
    + Reflect in 60% of final grade
* Assignments contain
    + Limited step-by-step software instructions
    + Questions ranging from fairly basic to very advanced
    + Some questions that are open-ended
    + Some parts that are optional - be selective
* Lab assignments broken up in many small parts - if you get stuck somewhere, you can skip ahead to another part without having to wait for instructor feedback

## Suggestions for Lab Assignments
* Don't leave the assignments to the last minute.
    + You can accurately estimate the time to finish it.
    + Doing assignment along with classes can help you better understand the classes and yield to higher quality of assignment
* Try to get work done during the scheduled class times, and ask questions. 
* Instructions are posted ahead of time and are largely self explanatory, so you can start them ahead of the lectures. 
* If you get stuck with something, contact the instructor or TA - don't struggle too long on your own (!)
    + During class 
    + E-mail 
    + Office hours or by appointment

## Project Guidelines 
* The emphasis should be on using GIS as a problem solving, analytical or research tool. 
* While some data collection effort is OK, most (if not all) of your data should already exist in usable form - at least 2/3 of the project time should be spent on analysis 
* You are welcome to explore other spatial modeling software, so you are not limited to ArcGIS, or to even to using only GIS software.

## Project Topics 
* You will choose your project topics by: 
    + Option 1: Select from a set of suggested projects  
    + Option 2: Expand on an existing lab assignment 
    + Option 3: Develop your own project
    
## Option 1: Suggested Project Topics 
* Advanced suitability modeling - More advanced techniques needed. 
* Least-cost path and corridor analysis for conservation - Developing a technique to determine the most appropriate linkages between existing conservation areas. 
* Home range estimation techniques - Comparison of various techniques to determine the home range for an individual. 
* Land cover change modeling - Deriving transition rules from a time series of images and simulating land cover change using these rules.
* Sea level rise impact and social vulnerability analysis - Estimate infrastructure or population at risk of future sea level rise and evaluate vulnerability.
* Advanced terrain analysis techniques - flow routing, DEM reconditioning, depression removal.
* Design webGIS using Leaflet and Javascript

## Option 2 
* Expand on lab assignments 
    + Expand upon the analysis in one of the lab assignments using the existing data; 
    + Applying a similar analysis to another dataset; 
    + Combing various analysis techniques with new and/or existing data into a new exercise. 
* The key requirement here is that you truly expand upon the existing exercises, in terms of data complexity or analysis techniques.

## Option 3 
* You are free to develop a project of your own 
  -a combination of some of the aspects described (e.g. expanding on several lab assignments using new software); 
  -or bringing in your own data and developing an analysis of your own design. 
* The key requirement here is that most of the data should be available in usable form at the outset of the project, so that you end up spending most of your time doing analysis. 

## Project Deliverables (1)
* Project Proposal (less than 1 page) 
    + Motivation for doing this project (4-5 sentences). Include any relevant citations/figures.
    + A clearly stated hypothesis (1-2 sentences).
    + An outline of the datasets you need and methods to analyze them.
* Project Report (5~6 pages) 
    + Background (0.5 page): Motivation of problem (2 points)
    + Hypothesis (0.5 pages): Succinct statement of problem (3 points)
    + Methodology (0.5 pages): Appropriate use of GIS (3 points)
    + Results (1.5 pages): Do results address hypothesis (4 points)
    + Discussion and Conclusions (1.5 pages): Interpretation of results (6 points)
    + Future Work (0.5 pages): Next steps (2 points)
    
## Project Deliverables (2)
* Poster
    - A succinct and comprehensible version of project report - documenting all major components in project report.
    - Consider how to deliver information efficiently and effectively in a limited space.
    - Produce in a print-ready format in 36" * 48" size (ppt, pdf or word)
* Report review 
    - Your review of other students' reports
* Powerpoint presentation 
    + <=15 mins in total (<=10 mins for presentation  and <=5 mins for Q&A and transition) 

## Project Timeline
* Project proposal due: Week 7 
    - Submit Word/pdf file to laulima
    - Feebacks will be given before spring break
* Report submission: Week 15
    - Submit word/pdf file using laulima
* Poster submission: Week 15
    - Submit word/ppt/pdf file using laulima
* Powerpoint presentations: Weeks 16-17
    - Submit ppt/pdf file using laulima
* Report review submission: Week 17
>>>>>>> 5603d93081f13a82139bb883f43c1379a05b280f
